/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utd.team6.workforceresearchguide.gui;

import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import utd.team6.workforceresearchguide.main.ApplicationController;

/**
 *
 * @author Michael
 */
public class GroupManagerDialog extends javax.swing.JDialog {

    ApplicationController app;
    DefaultListModel<String> listModel;
    String repPath;
    
    JFileChooser chooser;
    
    /**
     * Creates new form GroupManagerDialog
     * @param repPath
     * @param app
     */
    public GroupManagerDialog(String repPath, ApplicationController app) {
        initComponents();
        this.app = app;
        
        listModel = new DefaultListModel<>();
        docList.setModel(listModel);
        this.repPath = repPath;
        
        chooser = new JFileChooser(repPath);
        chooser.setMultiSelectionEnabled(true);
        
        //Get the groups
        for(String group:app.getGroups()){
            groupDropdown.addItem(group);
        }
    }

    /**
     * Refreshes the document list.
     */
    public void groupChanged(){
        listModel.removeAllElements();
        String group = (String)groupDropdown.getSelectedItem();
        for(String path:app.getGroupDocuments(group)){
            listModel.addElement(path);
        }
    }
    
    /**
     * Shows this dialog.
     */
    public void showDialog(){
        setModal(true);
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        docList = new javax.swing.JList<>();
        groupDropdown = new javax.swing.JComboBox<>();
        deleteGroupButton = new javax.swing.JButton();
        addFilesButton = new javax.swing.JButton();
        removeFilesButton = new javax.swing.JButton();
        addGroupButton = new javax.swing.JButton();

        docList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(docList);

        groupDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupDropdownActionPerformed(evt);
            }
        });

        deleteGroupButton.setText("Delete Group");
        deleteGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGroupButtonActionPerformed(evt);
            }
        });

        addFilesButton.setText("Add Files To Group");
        addFilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFilesButtonActionPerformed(evt);
            }
        });

        removeFilesButton.setText("Remove Selected From Group");
        removeFilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFilesButtonActionPerformed(evt);
            }
        });

        addGroupButton.setText("Add Group");
        addGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(groupDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addGroupButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteGroupButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addFilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeFilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteGroupButton)
                    .addComponent(addGroupButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFilesButton)
                    .addComponent(removeFilesButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupDropdownActionPerformed
        groupChanged();
    }//GEN-LAST:event_groupDropdownActionPerformed

    private void addGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroupButtonActionPerformed
        String group = JOptionPane.showInputDialog(rootPane, "Name the group.");
        if(group != null && !group.isEmpty()){
            app.addGroup(group);
            listModel.addElement(group);
            groupDropdown.setSelectedItem(group);
            groupChanged();
        }
    }//GEN-LAST:event_addGroupButtonActionPerformed

    private void deleteGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGroupButtonActionPerformed
        String group = (String)groupDropdown.getSelectedItem();
        app.removeGroup(group);
        groupDropdown.removeItem(group);
        groupChanged();
    }//GEN-LAST:event_deleteGroupButtonActionPerformed

    private void docListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docListMouseClicked
        if(evt.getClickCount()>1){
            DocumentDetailsDialog details = app.getInfoFactory().getDetailsDialog(docList.getSelectedValue(), true);
            details.setModal(true);
            details.setLocationRelativeTo(this);
            details.setVisible(true);
        }
    }//GEN-LAST:event_docListMouseClicked

    private void addFilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFilesButtonActionPerformed
        int result = chooser.showDialog(this, "Add File");
        if(result == JFileChooser.APPROVE_OPTION){
            File[] files = chooser.getSelectedFiles();
            String group = (String)groupDropdown.getSelectedItem();
            for(File f:files){
                String docPath = f.getAbsolutePath();
                //Add the file to the group
                app.addDocumentToGroup(group, docPath);
                listModel.addElement(docPath);
            }
        }
    }//GEN-LAST:event_addFilesButtonActionPerformed

    private void removeFilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFilesButtonActionPerformed
        String group = (String)groupDropdown.getSelectedItem();
        for(String selection:docList.getSelectedValuesList()){
            app.removeDocumentFromGroup(group, selection);
            listModel.removeElement(selection);
        }
    }//GEN-LAST:event_removeFilesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupManagerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupManagerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupManagerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupManagerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GroupManagerDialog("",null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFilesButton;
    private javax.swing.JButton addGroupButton;
    private javax.swing.JButton deleteGroupButton;
    private javax.swing.JList<String> docList;
    private javax.swing.JComboBox<String> groupDropdown;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeFilesButton;
    // End of variables declaration//GEN-END:variables
}
