/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utd.team6.workforceresearchguide.gui.repscan;

import utd.team6.workforceresearchguide.main.issues.AddedFileIssue;

/**
 *
 * @author Michael
 */
public class AddedFileIssuePanel extends javax.swing.JPanel {

    private final AddedFileIssue issue;
    
    /**
     * Creates new form SingleFileIssue
     * @param iss
     */
    public AddedFileIssuePanel(AddedFileIssue iss) {
        initComponents();
        issue = iss;
        documentCheckbox.setText(issue.getAddedFile().getPath());
    }

    public void setSelected(boolean selected){
        documentCheckbox.setSelected(selected);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        documentCheckbox = new javax.swing.JCheckBox();

        jButton1.setText("Info");

        documentCheckbox.setSelected(true);
        documentCheckbox.setText("Document Path");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(documentCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(documentCheckbox)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox documentCheckbox;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
