/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utd.team6.workforceresearchguide.gui.repscan;

import java.awt.event.ActionListener;

/**
 *
 * @author Michael
 */
public class RepositoryScanWaitPanel extends javax.swing.JPanel {

    public static final int SCAN_ANIMATION_DELAY = 900;
    private static final int SCAN_COUNT_MAX = 3;

    int scanCount = 0;

    private final ActionListener cancel;

    /**
     * Creates new form RepositoryScanWaitPanel
     *
     * @param cancel
     */
    public RepositoryScanWaitPanel(ActionListener cancel) {
        initComponents();
        this.cancel = cancel;
    }

    /**
     * Starts the animation over from the start with the specified text.
     *
     * @param text
     */
    public void resetAnimation(String text) {
        scanAnimationLabel.setText(text);
        scanCount = 0;
    }

    /**
     * Moves the animation by one step.
     *
     * @param text
     */
    public void updateAnimation(String text) {
        if (scanCount < SCAN_COUNT_MAX) {
            scanCount++;
            String dot = "";
            for(int i=0;i<scanCount;i++){
                dot+=".";
            }
            scanAnimationLabel.setText(dot + text + dot);
        } else {
            scanCount = 0;
            scanAnimationLabel.setText(text);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scanAnimationLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        scanAnimationLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        scanAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scanAnimationLabel.setText("Scanning Repository");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scanAnimationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(scanAnimationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancel.actionPerformed(evt);
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel scanAnimationLabel;
    // End of variables declaration//GEN-END:variables
}
